### PR TITLE
refactor: atomWithHash

### PR DESCRIPTION
**Pull request by dai-shi**
without depending on `atomWithStorage`.
It may behave a little differently, but all tests are passing.

### CODE REVIEW

**Comment by dai-shi** [comment]
@Eunanibus @matannahmani @notsidney @pakettiale @Davasny @msdrigg @jakkku @V-Mann-Nick @austinwoon 

Sorry for several mentions, but can anyone check if it works as before?

https://ci.codesandbox.io/status/jotaijs/jotai-location/pr/13
(Find "Local Install Instructions")

**Comment by matannahmani** [comment]
@dai-shi seems to be fine, but I couldn't get atom hydrated while using SSR:
image

**Comment by dai-shi** [comment]
Isn't it impossible in v2 even before this refactor?

**Comment by matannahmani** [comment]
@dai-shi correct I completely forgotten about it

**Comment by AjaxSolutions** [comment]
Can you merge this PR?

**Pull request merged**
